import "./globals.css";
import Navbar from "./components/Navbar";
import Banner from "./components/Banner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Banner />
        <Navbar className="sticky" />

        {children}
      </body>
    </html>
  );
}
